config/routes.rb
Sorteos::Application.routes.draw do
  get "asistencia" => "people#asistencia", :as => :asistencia
  get "people/premiados" => "people#premiados", :as => :premiados_people
  resources :people
  get "sorteo" => "people#sorteo", :as => :sorteo
  get "premiar" => "people#premiar", :as => :premiar
  get "registro" => "people#registro", :as => :registro
  post "registrar" => "people#registrar", :as => :registrar

end

app/models/person.rb
class Person < ActiveRecord::Base
  validates :num_empleado, :presence => true, :uniqueness => true
  validates :nombre, :presence => true
  validates :dependencia, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/people_controller.rb
#encoding:utf-8

class PeopleController < ApplicationController
  # GET /people
  # GET /people.json
  def index
    @people = Person.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @people }
    end
  end
  
  def premiados
    @people = Person.where(premiado: true)
    
    respond_to do |format|
      format.html { render action: 'index' }
      format.json { render json: @people }
    end
    
  end

  # GET /people/1
  # GET /people/1.json
  def show
    @person = Person.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/new
  # GET /people/new.json
  def new
    @person = Person.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/1/edit
  def edit
    @person = Person.find(params[:id])
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(params[:person])

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render json: @person, status: :created, location: @person }
      else
        format.html { render action: "new" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /people/1
  # PUT /people/1.json
  def update
    @person = Person.find(params[:id])

    respond_to do |format|
      if @person.update_attributes(params[:person])
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person = Person.find(params[:id])
    @person.destroy

    respond_to do |format|
      format.html { redirect_to people_url }
      format.json { head :ok }
    end
  end
  
  def sorteo
    
    respond_to do |format|
      format.html # sorteo.html.erb
      format.json { render json: 'sorteo' }
    end 
  end
  
  def premiar
    count = Person.where(:activo => true,:premiado => false).count
    if count == 0
      ganador = "No hay más participantes"
    else
      rand = Random.new.rand(1..count)
      people = Person.where(:activo => true,:premiado => false).shuffle
      person = people[rand-1]
      person.update_attribute(:premiado, true)
      ganador = "#{person.num_empleado} #{person.nombre} - #{person.dependencia}"      
    end
    
    respond_to do |format|
      format.html # premiar.html.erb
      format.json { render json: ganador }
    end 
  end
  
  
  def registro    
    respond_to do |format|
      format.html # registrar.html.erb
      format.json { render json: 'registrar' }
    end 
  end
  
  def registrar
    num_empleado = params[:num_empleado]
    @person = Person.find_by_num_empleado(num_empleado)
    if @person.nil?
      @not_found = true
    else
      @person.update_attribute(:activo, true)      
    end
    
    respond_to do |format|
      format.html { render :action => "registro"}
      format.json { render json: ganador }
    end 
  end

  def asistencia
    @people = Person.where("activo = ?", true).paginate(:page => params[:page], :per_page => 100).order("nombre")
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sorteos</title>
  <%= stylesheet_link_tag    "application", "styles" %>
  <%= javascript_include_tag "application" %>
  <%= yield :head %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/people/_form.html.erb
<div style="margin-top: 125px;">
  <h1>Registro de personas</h1>
  <%= form_for(@person) do |f| %>
    <% if @person.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

        <ul>
        <% @person.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :num_empleado %><br />
      <%= f.text_field :num_empleado %>
    </div>
    <div class="field">
      <%= f.label :nombre %><br />
      <%= f.text_field :nombre %>
    </div>
    <div class="field">
      <%= f.label :dependencia %><br />
      <%= f.text_field :dependencia %>
    </div>
    <div class="field">
      <%= f.label :antiguedad, 'Antigüedad' %><br/>
      <%= f.text_field :antiguedad %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/people/asistencia.html.erb
<% content_for :head do %>
<style>
  table {
    color: #333;
  max-width: 100%;
  border-collapse: collapse;
  border-spacing: 0;
  background-color: transparent;
}
.table {
  width: 100%;
  margin-bottom: 18px;
}
.table th,
.table td {
  padding: 8px;
  line-height: 18px;
  text-align: left;
  vertical-align: top;
  border-top: 1px solid #dddddd;
}
.table th {
  font-weight: bold;
}
.table thead th {
  vertical-align: bottom;
}
.table-condensed th,
.table-condensed td {
  padding: 4px 5px;
}
</style>
<% end %>

<div style="margin-top: 130px;">
  <div style="margin-bottom: 12px;" class="digg_pagination"><%= will_paginate @people %></div>

<table class="table table-condensed ">
  <thead>
    <th>Número de empleado</th>
    <th>Nombre</th>
    <th>Dependencia</th>
  </thead>
  <tbody>
  <% @people.each do |person| %>
  <tr>
    <td><%= person.num_empleado %></td>
    <td><%= person.nombre %></td>
    <td><%= person.dependencia %></td>
  </tr>
      
    
  <% end %>
  </tbody>
</table>

  <div style="margin-top: 12px;" class="digg_pagination"><%= will_paginate @people %></div>
  </div>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<h1>Listing people</h1>

<table>
  <tr>
    <th>Num empleado</th>
    <th>Nombre</th>
    <th>Dependencia</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @people.each do |person| %>
  <tr>
    <td><%= person.num_empleado %></td>
    <td><%= person.nombre %></td>
    <td><%= person.dependencia %></td>
    <td><%= link_to 'Show', person %></td>
    <td><%= link_to 'Edit', edit_person_path(person) %></td>
    <td><%= link_to 'Destroy', person, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/registro.html.erb
<div id="container1">
<h6>Registro de Participantes</h6>
<% unless @person.nil? %>
  <h3><%= @person.nombre %></h3>
  <h6>Dependencia: <%= @person.dependencia %></h6>
  <% unless @person.antiguedad.nil? %>
  <h3 style="color: #942a25;">Antigüedad: <%= @person.antiguedad %></h3>
  <% end %>
  
<% end %>

<% unless @not_found.nil? %>
<h2>Persona no encontrada </h2>
<% end %>

<%= form_tag(registrar_path, :method => :post) do %>
  <p>
    <%= label_tag :num_empleado, "Número de Empleado" %>
    <%= text_field_tag :num_empleado %>
  </p>
  <p>
    <%= submit_tag "Registrar"%>
  </p>
<% end %>
</div>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Num empleado:</b>
  <%= @person.num_empleado %>
</p>

<p>
  <b>Nombre:</b>
  <%= @person.nombre %>
</p>

<p>
  <b>Dependencia:</b>
  <%= @person.dependencia %>
</p>


<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>

app/views/people/sorteo.html.erb
		<div id="container">Bienvenido!</div>

		<input type="submit" id="userText" val="Obtener Ganador" />